services:
  - type: web
    name: chatgpt-automation-vps
    runtime: python
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: ENV
        value: production
    autoDeploy: true
